version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - proshop-network

  backend:
    image: proshop-backend:latest
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/proshop
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - proshop-network

  frontend:
    image: proshop-frontend:latest
    container_name: frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - proshop-network

  prometheus:
    image: proshop-prometheus:latest
    build:
      context: .
      dockerfile: prometheus/Dockerfile.prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - proshop-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000' # Accessible sur votre PC via http://localhost:3001
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - proshop-network
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - proshop-network
    restart: unless-stopped

networks:
  proshop-network:
    driver: bridge

volumes:
  mongo_data:
  grafana_data:
