global:
  scrape_interval: 15s # Temps entre chaque récupération de métriques

scrape_configs:
  # 1. Métriques de Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Métriques de la machine / des conteneurs (via node-exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Utilise le nom du service docker-compose

  # 3. Métriques de votre application ProShop Backend
  - job_name: 'proshop-backend'
    scrape_interval: 5s
    metrics_path: '/metrics' # L'URL que Prometheus va interroger
    static_configs:
      - targets: ['backend:5000'] # Utilise le nom du service backend
